# Dataset Explorer
Use this notebook to explore the samples dataset after it has been cleaned and organized.  Make sure to run Luigi to generate data before exploring it here.

In [1]:
import pandas as pd

# CONAGUA samples
Use this section to explore the dataset of processed samples.

In [2]:
samples = pd.read_csv('../data/processed/samples.csv', index_col=0)

# Number of independent samples
samples.shape

(3951, 10)

In [3]:
# 10 random rows from the samples dataset
samples.sample(10)

,site,type,latitude,longitude,arsenic,cadmium,chromium,mercury,lead,fluoride
3371,OCPBC4287M1,Lagoon,32.158742,-115.300952,7.025,0.00,0.000000,0.057500,0.000000,NaN
523,DLDUR696,Well,25.062150,-103.728870,81.000,0.00,0.000000,0.000000,0.000000,1231.3
3902,OCRBR5131M1,River,26.085370,-98.264890,0.000,0.00,5.171667,0.091667,0.000000,NaN
1927,DLTAB5356,Well,17.890833,-93.524722,0.000,0.00,0.000000,0.000000,0.000000,6.8
1314,DLMIC1772,Well,19.701130,-100.545570,7.300,0.33,9.200000,0.400000,0.900000,269.0
358,DLCOA490,Dam,29.519440,-101.252590,0.000,0.00,0.000000,0.000000,0.000000,NaN
420,DLCOL554,River,18.835180,-103.625050,0.000,0.00,14.116667,0.009667,5.583333,NaN
1510,DLPUE2022M1,River,19.115480,-98.227500,0.000,0.00,7.953333,0.111667,2.758333,NaN
3238,OCNOR4058,Dam,29.046880,-109.663000,0.000,0.00,0.000000,0.027000,0.000000,NaN
3622,OCPNO4678,River,25.708990,-108.341110,1.575,0.00,9.150000,0.011333,1.866667,NaN

# INEGI towns
Use this section to explore the dataset of towns and their estimated contaminant exposure.

In [4]:
towns = pd.read_csv('../data/processed/towns_with_exposure.csv', index_col=0)

In [5]:
towns.shape

(43504, 14)

In [6]:
# 10 random rows from the towns dataset
towns.sample(10)

,state,municipality,name,population,longitude,latitude,geometry,arsenic,cadmium,chromium,mercury,lead,fluoride,number_nearby_sites
10292,Sonora,San Ignacio Río Muerto,EL ALHUATE,9,-110.194722,27.350000,POINT (-110.194722222 27.35),16.891667,0.000000,6.533333,0.110167,0.000000,NaN,1.0
26312,Hidalgo,Atotonilco el Grande,SAUZ SABINO,318,-98.772778,20.354167,POINT (-98.7727777778 20.3541666667),0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.0
30417,Guanajuato,Romita,SAN JOSÉ DE TUNA AGRIA,11,-101.696389,20.845833,POINT (-101.696388889 20.8458333333),9.275000,0.000000,0.000000,0.025000,0.000000,1132.650000,2.0
17984,Nuevo León,Gral. Zaragoza,LA BARRANCA,16,-99.800556,23.981111,POINT (-99.8005555556 23.9811111111),0.000000,0.000000,2.626667,0.000000,0.000000,NaN,1.0
41140,Baja California,Ensenada,PARCELA NÚMERO TREINTA Y SEIS (TRIPLE A),14,-116.559722,31.758611,POINT (-116.559722222 31.7586111111),0.000000,0.000000,0.000000,0.000000,0.000000,1185.700000,2.0
30086,Guanajuato,Moroleón,COLONIA EL LLAVERO,14,-101.218333,20.094722,POINT (-101.218333333 20.0947222222),3.133333,0.116667,1.433333,0.233333,0.666667,529.566667,3.0
24798,Jalisco,Puerto Vallarta,BOCA DE TOMATES,7,-105.278889,20.671944,POINT (-105.278888889 20.6719444444),23.261111,0.666667,14.655556,0.146444,16.205556,NaN,3.0
7723,Tabasco,Centla,LA MONTAÑA,198,-92.937778,18.420833,POINT (-92.93777777780001 18.4208333333),0.000000,0.000000,0.441667,0.000000,1.050000,NaN,2.0
35148,Chiapas,Cintalapa,EL TOMATAL,12,-93.784444,16.664444,POINT (-93.78444444440001 16.6644444444),0.000000,0.000000,0.000000,0.000000,0.000000,NaN,1.0
11967,San Luis Potosí,Ciudad Valles,RANCHO LOS CUATES,1,-99.103889,22.030000,POINT (-99.10388888889999 22.03),0.000000,0.000000,7.505000,0.000000,0.000000,NaN,1.0